// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/electionPeriod": {
            "post": {
                "description": "Endpoint to insert election periods, should only be used to insert missing/hisotical data",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Election periods"
                ],
                "summary": "Inserts election periods",
                "parameters": [
                    {
                        "description": "the election periods that are going to be inserted",
                        "name": "periods",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ElectionPeriod"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ElectionPeriod"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/electionPeriod/range/{from}/{to}/": {
            "get": {
                "description": "Returns all election periods that took place in a given timespan",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Election periods"
                ],
                "summary": "Get election periods by timespan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "from The beginning of the selected timespan",
                        "name": "from",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "The end of the selected timespan",
                        "name": "to",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ElectionPeriod"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/electionPeriod/{year}": {
            "get": {
                "description": "Returns the election periods that took place in a given year",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Election periods"
                ],
                "summary": "Get the election period of a certain year",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "the searched year",
                        "name": "year",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ElectionPeriod"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Candidate": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "perks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Perk"
                    }
                }
            }
        },
        "model.ElectionPeriod": {
            "type": "object",
            "properties": {
                "candidates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Candidate"
                    }
                },
                "end": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                },
                "winner": {
                    "$ref": "#/definitions/model.Candidate"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "model.Perk": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Mayor API",
	Description:      "This is the API for the Mayor votings",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
